from pydantic import BaseModel, Field


class AIExplanation(BaseModel):
    """
    Structured response generated by Gemini for one laboratory result.
    """

    explanation: str = Field(
        ...,
        description=(
            "A clear, concise, patient-friendly explanation of "
            "what the laboratory result means."
        ),
    )

    next_step: str = Field(
        ...,
        description=(
            "A practical and appropriate next step based on the "
            "laboratory result and its severity."
        ),
    )